name: notes_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4
  flutter_riverpod: ^1.0.4
  dartz: ^0.10.1
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.5.3+2
  auto_route: ^5.0.1
  lottie: ^1.4.2
  google_sign_in: ^5.4.2
  flutter_secure_storage: ^6.0.0
  font_awesome_flutter: ^10.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  auto_route_generator: ^5.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logInPageImages/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/logInPageImages/
    - assets/signUpPageImages/





